name:                origin
version:             0.1.0.0
github:              "alexpeits/origin"
license:             BSD3
author:              "Alex Peitsinis"
maintainer:          "alexpeitsinis@gmail.com"
copyright:           "Copyright (c) 2019 Alex Peitsinis"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexpeits/origin#readme>

ghc-options:
- -Wall
- -Wno-unticked-promoted-constructors

dependencies:
- base >= 4.7 && < 5
- barbies
- higgledy
- optparse-applicative
- validation

library:
  source-dirs: src
  default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators

tests:
  origin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - origin

  readme-test:
    main:                README.lhs
    ghc-options:
    - -threaded
    - -Wall
    - -fno-warn-name-shadowing
    - -fno-warn-missing-signatures
    - -fno-warn-unused-top-binds
    - -fno-warn-type-defaults
    - -pgmL markdown-unlit
    dependencies:
    - origin
    - barbies
    - higgledy
    build-tools:
    - markdown-unlit

executables:
  example:
    main:                Example.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is
    - Example
    dependencies:
    - origin
