name:                harg
version:             0.1.0.0
github:              "alexpeits/harg"
license:             BSD3
author:              "Alex Peitsinis"
maintainer:          "alexpeitsinis@gmail.com"
copyright:           "Copyright (c) 2019 Alex Peitsinis"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            System, CLI, Options, Parsing

description:         Please see the README on GitHub at <https://github.com/alexpeits/harg#readme>

ghc-options:
- -Wall
- -Wno-unticked-promoted-constructors

dependencies:
- base >= 4.7 && < 5
- barbies
- higgledy
- optparse-applicative
- validation

library:
  source-dirs: src
  default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators

tests:
  harg-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - harg

  readme-test:
    main: README.lhs
    ghc-options:
    - -threaded
    - -Wall
    - -fno-warn-name-shadowing
    - -fno-warn-missing-signatures
    - -fno-warn-unused-top-binds
    - -fno-warn-type-defaults
    - -pgmL markdown-unlit
    dependencies:
    - harg
    - barbies
    - higgledy
    build-tools:
    - markdown-unlit

executables:
  example:
    main: Example.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is
    - Example
    dependencies:
    - harg
