name: "Build and test"
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  cabal-nix:
    name: cabal+nix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["ghc865", "ghc884"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - name: Install nix
      uses: cachix/install-nix-action@v13
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: alexpeits-gh-actions
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Cache ~/.cabal/packages and ~/.cabal/store
      uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.nixpkgs }}-${{ matrix.ghc }}
    - name: Setup cabal
      run: nix-shell --argstr compiler ${{ matrix.ghc }} --arg withHoogle false --run 'cabal update'
    - name: Build
      run: nix-shell --argstr compiler ${{ matrix.ghc }} --arg withHoogle false --run 'cabal new-build'
    - name: Test
      run: nix-shell --argstr compiler ${{ matrix.ghc }} --arg buildDocsTest true --arg withHoogle false --run 'cabal new-test -fbuilddocstest'
    - name: Haddock
      run: nix-shell --argstr compiler ${{ matrix.ghc }} --arg withHoogle false --run 'cabal new-haddock --haddock-options="--show-all"'
  stack:
    name: stack
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.3.1"]
        ghc: ["8.6.5", "8.8.4"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - uses: actions/setup-haskell@v1.1.4
      name: Setup ghc+stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
    - uses: actions/cache@v2.1.5
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.stack }}
    - name: Build
      run: stack --stack-yaml=stack-${{ matrix.ghc }}.yaml build
    - name: Test
      run: stack --stack-yaml=stack-${{ matrix.ghc }}.yaml test --flag harg:builddocstest
