name: "Build and test"
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  cabal-nix:
    name: Build and test with cabal+nix
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Install nix
      uses: cachix/install-nix-action@v10
    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: alexpeits-gh-actions
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Cache ~/.cabal/packages and ~/.cabal/store
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
        key: ${{ runner.os }}-ghc-8.6.5
    - name: Setup cabal
      run: make cabal-update
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Haddock
      run: make haddock
  stack:
    name: Build and test with stack
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.3.1"]
        ghc: ["8.6.5"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - uses: actions/setup-haskell@v1.1
      name: Setup ghc+stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.stack }}
    - name: Build
      run: stack --stack-yaml=stack-${{ matrix.ghc }}.yaml build
    - name: Test
      run: stack --stack-yaml=stack-${{ matrix.ghc }}.yaml test
