name: "Build and test"
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Install nix
      uses: cachix/install-nix-action@v10
    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: alexpeits-gh-actions
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build
      run: |
        nix-build
    - name: Test
      run: |
        echo 'tests: True' > cabal.project.local
        nix-shell --command 'cabal new-test'
