name: "Build and test"
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Install nix
      uses: cachix/install-nix-action@v10
    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: alexpeits-gh-actions
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Setup cabal user-config
      run: nix-shell --run 'cabal user-config update'
    - name: Build
      run: |
        ls -la
        nix-shell --run 'cabal new-build'
    - name: Configure cabal project
      run: |
        ls -la
        nix-shell --run 'cabal new-build'
        make cabal-configure
        cat cabal.project.local
        ls -la
    - name: Build
      run: cabal new-build
    - name: Build
      run: cabal new-test
