name: "Build and test"
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Install nix
      uses: cachix/install-nix-action@v10
    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: alexpeits-gh-actions
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Setup cabal
      run: nix-shell --run 'cabal update'
    - name: Cache ~/.cabal/packages and ~/.cabal/store
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
        key: ${{ runner.os }}-ghc-8.6.5
    - name: Build
      run: nix-shell --run 'cabal new-build'
    - name: Test
      run: nix-shell --run 'cabal new-test'
    - name: Haddock
      run: nix-shell --run 'cabal new-haddock'
