name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [main]
  schedule:
    # additionally run once per week (At 00:00 on Sunday) to maintain cache
    - cron: '0 0 * * 0'

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.8.1.0"]
        ghc:
          - "8.6.5"
          - "8.8.4"
          - "8.10.7"
          - "9.0.2"
          - "9.2.5"
          - "9.4.4"
    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2.0
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Configure
      run: |
        cabal configure --enable-tests --enable-benchmarks --enable-documentation --test-show-details=direct --write-ghc-environment-files=always -f builddocstest

    - name: Freeze
      run: |
        cabal freeze -f builddocstest

    - uses: actions/cache@v3
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Install build-tool dependencies
      run: |
        cabal install markdown-unlit
  
    - name: Install dependencies
      run: |
        cabal build all --only-dependencies -f builddocstest

    - name: Build
      run: |
        cabal build all -f builddocstest

    - name: Test
      run: |
        cabal test all -f builddocstest

    - name: Documentation
      run: |
        cabal haddock

  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack: ["2.7.5"]
        ghc: ["8.6.5", "8.8.4", "8.10.7", "9.0.2", "9.2.5"]

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2.0
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Install dependencies
      run: |
        stack build --stack-yaml=stack-${{ matrix.ghc }}.yaml --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      run: |
        stack build --stack-yaml=stack-${{ matrix.ghc }}.yaml --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --stack-yaml=stack-${{ matrix.ghc }}.yaml --system-ghc
